version: '3.8'

services:
  scraper:
    build: .
    container_name: fb-scraper
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./userData:/usr/src/app/userData
      - ./public/images:/usr/src/app/public/images
      - ./configs:/usr/src/app/configs
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHROMIUM_PATH=${CHROMIUM_PATH}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=${PUPPETEER_SKIP_CHROMIUM_DOWNLOAD}
      - USER_DATA_DIR=${USER_DATA_DIR}
      - PORT=${PORT}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    restart: unless-stopped
    # Add healthcheck to ensure the service is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  scraper_images:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/public/images
      o: bind 