version: '3.8'

services:
  scraper:
    build: .
    container_name: fb-scraper
    ports:
      - "3000:3000"
    volumes:
      - ./userData:/usr/src/app/userData
      - ./public/images:/usr/src/app/public/images
    environment:
      - NODE_ENV=production
      - CHROMIUM_PATH=/usr/bin/chromium
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - USER_DATA_DIR=/usr/src/app/userData
    restart: unless-stopped
    # Add healthcheck to ensure the service is running properly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  scraper_images:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/public/images
      o: bind 